### ISSUE TITLE
Stripping out MathML from the RSS feed

### ISSUE THREAD

**Issue by jeffkaufman** [kagisearch/smallweb#10]
It looks like you're stripping MathML out of the RSS feed -- is that intentional, or are you using an older sanitizer that doesn't recognize it?  For example, my [RSS feed](https://www.jefftk.com/news.rss) for my [most recent post](https://www.jefftk.com/p/weekly-incidence-vs-cumulative-infections) has:

    &lt;math display=&quot;block&quot;&gt;
    &lt;msup&gt;&lt;mi&gt;e&lt;/mi&gt;
          &lt;mrow&gt;&lt;mi&gt;k&lt;/mi&gt;&lt;mi&gt;t&lt;/mi&gt;&lt;/mrow&gt;&lt;/msup&gt;
    &lt;/math&gt;

Which shows up in [your RSS feed](https://kagi.com/api/v1/smallweb/feed) as:

    e
          kt

**Comment by vprelovac** [comment]
I was not able to reproduce this. Was it a glitch and everything is fine now?

<img width="2543" alt="Screenshot 2023-09-08 at 16 10 01" src="https://github.com/kagisearch/smallweb/assets/4319401/8a18ca97-cea8-4930-87a0-d9ac748e2655">

**Comment by vprelovac** [comment]
@jeffkaufman

**Comment by jeffkaufman** [comment]
I'm also not able to reproduce this now.  In the same place I now see, correctly:

```
&lt;math display=&#34;block&#34; xmlns=&#34;http://www.w3.org/1998/Math/MathML&#34;&gt;
&lt;msup&gt;&lt;mi&gt;e&lt;/mi&gt;
      &lt;mrow&gt;&lt;mi&gt;k&lt;/mi&gt;&lt;mi&gt;t&lt;/mi&gt;&lt;/mrow&gt;&lt;/msup&gt;
&lt;/math&gt;
```

Strange!
