### ISSUE TITLE
Feeds in other languages?

### ISSUE THREAD

**Issue by matmat** [kagisearch/smallweb#110]
Firts, thanks for starting this initiative! Love it.

I have started curating a list of urls for feeds meeting the same criteria as the main ones but in Swedish (my native language) and in a file called smallweb-sv.txt. Would that be something that would be accepted in the main repo?

My WIP is here: https://github.com/matmat/smallweb/blob/smallweb-sv/smallweb-sv.txt

**Comment by vprelovac** [comment]
It is not something we would pursue right now as this becomes useful only once we have coverage for at least the major languages.

**Comment by matmat** [comment]
Understood. I will keep my branch updated, feel free to merge it at any time.
