### ISSUE TITLE
High volume feeds

### ISSUE THREAD

**Issue by matmat** [kagisearch/smallweb#114]
There are some feeds with a very high volume of posts currently in the list. Should there be a limit for this in the criteria for inclusion?

Here are the ones with recent items that have an average of >5 posts per day.

| Average posts per day | Average posts per week | Feed URL                                                | Newest post date             | Oldest post date             | Number of posts |
|-----------------------|------------------------|---------------------------------------------------------|------------------------------|------------------------------|-----------------|
| 15.0                  | 105.0                  | https://soft-wa.re/podcast.rss                          | 2023-10-19T01:35:39+00:00Z  | 2023-10-19T01:35:38+00:00Z  | 15              |
| 12.5                  | 87.5                   | https://maique.eu/feed.xml                              | 2023-10-19T16:09:29+00:00Z  | 2023-10-17T14:12:04+00:00Z  | 25              |
| 10.0                  | 70.0                   | https://bottledaux.com/feed/                            | 2023-10-18T22:22:26+00:00Z  | 2023-10-17T02:56:13+00:00Z  | 10              |
| 10.0                  | 70.0                   | https://feeds.feedburner.com/thisisnthappiness         | 2023-10-19T16:02:47+00:00Z  | 2023-10-16T19:08:11+00:00Z  | 20              |
| 10.0                  | 70.0                   | https://jabberwocking.com/feed/                         | 2023-10-19T17:11:30+00:00Z  | 2023-10-18T16:42:35+00:00Z  | 10              |
| 10.0                  | 70.0                   | https://jacklimpert.com/feed/                           | 2023-10-19T15:30:16+00:00Z  | 2023-10-18T20:27:47+00:00Z  | 10              |
| 10.0                  | 70.0                   | https://johnmenadue.com/feed/                           | 2023-10-18T17:58:41+00:00Z  | 2023-10-17T17:57:46+00:00Z  | 10              |
| 10.0                  | 70.0                   | https://putah-creek.tumblr.com/rss                      | 2023-10-19T12:54:35+00:00Z  | 2023-10-17T04:06:24+00:00Z  | 20              |
| 10.0                  | 70.0                   | https://www.fullmoonfiberart.com/feed/                  | 2023-10-19T15:34:33+00:00Z  | 2023-10-17T21:53:52+00:00Z  | 10              |
| 10.0                  | 70.0                   | https://www.lesswrong.com/feed.xml                      | 2023-10-19T16:48:00+00:00Z  | 2023-10-18T20:39:34+00:00Z  | 10              |
| 10.0                  | 70.0                   | https://www.thepassivevoice.com/feed/                   | 2023-10-19T17:03:29+00:00Z  | 2023-10-18T04:02:56+00:00Z  | 10              |
| 9.1                   | 63.6                   | https://www.jvt.me/feed.xml                             | 2023-10-19T13:10:04+00:00Z  | 2023-10-07T15:23:00+00:00Z  | 100             |
| 8.6                   | 60.0                   | https://feeds.kottke.org/main                           | 2023-10-19T17:12:18+00:00Z  | 2023-10-11T19:29:48+00:00Z  | 60              |
| 7.5                   | 52.5                   | https://feeds.feedblitz.com/marginalrevolution&x=1      | 2023-10-19T15:32:23+00:00Z  | 2023-10-16T18:03:52+00:00Z  | 15              |
| 6.3                   | 43.8                   | https://itstartswithabirthstone.blogspot.com/feeds/posts/default | 2023-10-19T16:42:00+00:00Z  | 2023-10-15T13:44:00+00:00Z  | 25              |
| 6.3                   | 43.8                   | https://samim.io/rss.xml                                | 2023-10-17T21:24:58+00:00Z  | 2023-10-13T19:31:24+00:00Z  | 25              |

**Comment by vprelovac** [comment]
I tend to leave them, for crawling. We still only show 2 most recent on the website, regardless of the count.
