### ISSUE TITLE
De-duplicate feed

### ISSUE THREAD

**Issue by vprelovac** [kagisearch/smallweb#154]
Would anyone care to deduplicate the list. 

Here is what I got with 

```
awk -F/ '{print $3}' smallweb.txt | sort | uniq -d | while read domain; do echo "$domain"; grep "$domain" smallweb.txt; echo ""; done
```

When duplicate feeds, we should keep just one that is more complete.

antonz.org
https://antonz.org/feed.xml
https://antonz.org/index.xml

ariadne.space
https://ariadne.space/atom.xml
https://ariadne.space/index.xml

bengtan.com
https://bengtan.com/index.xml
https://bengtan.com/interesting-things/index.xml

benjamincongdon.me
https://benjamincongdon.me/blog/feed.xml
https://benjamincongdon.me/feed.xml

bhavukjain.com
https://bhavukjain.com/feed.xml
https://bhavukjain.com/rss.xml

bitsofco.de
https://bitsofco.de/feed/feed.xml
https://bitsofco.de/rss

bitspook.in
https://bitspook.in/archive/feed.xml
https://bitspook.in/blog/feed.xml

blog.bofh.it
https://blog.bofh.it/?format=atom
https://blog.bofh.it/debian/?format=atom

blog.computationalcomplexity.org
https://blog.computationalcomplexity.org/feeds/posts/default
https://blog.computationalcomplexity.org/feeds/posts/default?alt=rss

blog.ctis.me
https://blog.ctis.me/blog/index.xml
https://blog.ctis.me/index.xml

blog.ncase.me
https://blog.ncase.me/feed.xml
https://blog.ncase.me/rss/

blogs.agu.org
https://blogs.agu.org/fromaglaciersperspective/
https://blogs.agu.org/geoedtrek/feed/
https://blogs.agu.org/georneys/
https://blogs.agu.org/landslideblog/feed/
https://blogs.agu.org/mountainbeltway/feed/
https://blogs.agu.org/wildwildscience/feed/

blogs.bl.uk
https://blogs.bl.uk/digitisedmanuscripts/atom.xml
https://blogs.bl.uk/european/atom.xml

blogs.gnome.org
https://blogs.gnome.org/alexl/feed/
https://blogs.gnome.org/hughsie/feed/
https://blogs.gnome.org/tbernard/feed/
https://blogs.gnome.org/wjjt/feed/

boffosocko.com
https://boffosocko.com/category/mathematics/feed/
https://boffosocko.com/feed/?cat=-484
https://boffosocko.com/kind/article/feed/

brandur.org
https://brandur.org/articles.atom
https://brandur.org/nanoglyphs.atom

buttondown.email
https://buttondown.email/alby/rss
https://buttondown.email/linotypebook/rss
https://buttondown.email/meticulous.serendipity/rss
https://buttondown.email/touchgrass/rss

chrisx.xyz
https://chrisx.xyz/blog/index.xml
https://chrisx.xyz/index.xml

cohost.org
https://cohost.org/Cadey-Bunny/rss/public.atom
https://cohost.org/tomforsyth/rss/public.atom

colinwalker.blog
https://colinwalker.blog/dailyfeed.xml
https://colinwalker.blog/livefeed.xml

cweiske.de
https://cweiske.de/feeds/news.xml
https://cweiske.de/tagebuch/feed/

danq.me
https://danq.me/feed/
https://danq.me/kind/article/feed/

daveon.design
https://daveon.design/atom.xml
https://daveon.design/rss.xml

declanbyrd.co.uk
https://declanbyrd.co.uk/journal/articles.xml
https://declanbyrd.co.uk/journal/feed.xml

embedded.fm
https://embedded.fm/blog?format=RSS
https://embedded.fm/blog?format=rss

entangledlogs.com
https://entangledlogs.com/archives/index.xml
https://entangledlogs.com/index.xml

gilmi.me
https://gilmi.me/blog/atom.xml
https://gilmi.me/blog/rss

granary.io
https://granary.io/url?input=html&output=rss&url=https://jamesg.blog
https://granary.io/url?url=https://werd.io/content/all/&input=html&output=atom&hub=https://bridgy-fed.superfeedr.com/

hacdias.com
https://hacdias.com/articles/feed.xml
https://hacdias.com/feed.xml

honzadvorsky.com
https://honzadvorsky.com/feed
https://honzadvorsky.com/feed.xml

hyperborea.org
https://hyperborea.org/feed.xml
https://hyperborea.org/journal/feed/

jasm1nii.xyz
https://jasm1nii.xyz/blog/articles/articles.xml
https://jasm1nii.xyz/blog/notes/notes.xml

jmtd.net
https://jmtd.net/log/feed
https://jmtd.net/log/index.atom

junkcharts.typepad.com
https://junkcharts.typepad.com/junk_charts/atom.xml
https://junkcharts.typepad.com/numbersruleyourworld/atom.xml

kwon.nyc
https://kwon.nyc/index.xml
https://kwon.nyc/notes/index.xml

lukesmith.xyz
https://lukesmith.xyz/index.xml
https://lukesmith.xyz/rss.xml

mathspp.com
https://mathspp.com/blog.atom
https://mathspp.com/blog.rss

mattbruenig.com
https://mattbruenig.com/comments/feed/
https://mattbruenig.com/feed/

matthewrocklin.com
https://matthewrocklin.com/atom.xml
https://matthewrocklin.com/blog/atom.xml

mccormick.cx
https://mccormick.cx/news/index.rss
https://mccormick.cx/news/tags/workblog.rss

nadh.in
https://nadh.in/blog/index.xml
https://nadh.in/index.xml

podviaznikov.com
https://podviaznikov.com/feed.xml
https://podviaznikov.com/writings/feed.xml

pxtl.ca
https://pxtl.ca/feed.xml
https://pxtl.ca/rss.xml

quentin.delcourt.be
https://quentin.delcourt.be/feeds/blog.xml
https://quentin.delcourt.be/feeds/links.xml

research.swtch.com
http://research.swtch.com/feed.atom
https://research.swtch.com/feed.atom

sobolevn.me
https://sobolevn.me/feed.xml
https://sobolevn.me/git-secret/feed.xml

stefan-marr.de
https://stefan-marr.de/feed/
https://stefan-marr.de/feed/index.xml

susam.net
https://susam.net/blog/feed.xml
https://susam.net/maze/feed.xml

theadhocracy.co.uk
https://theadhocracy.co.uk/rss-articles.xml
https://theadhocracy.co.uk/rss.xml

theprivacydad.com
https://theprivacydad.com/feed/
https://theprivacydad.com/feed/?type=rss

thoughts.hnr.fyi
https://thoughts.hnr.fyi/feed.xml
https://thoughts.hnr.fyi/index.xml

tomaugspurger.net
https://tomaugspurger.net/feeds/all.atom.xml
https://tomaugspurger.net/index.xml

tomgamon.com
https://tomgamon.com/atom.xml
https://tomgamon.com/index.xml

tomstu.art
https://tomstu.art/articles.atom
https://tomstu.art/feed.atom

tratt.net
https://tratt.net/laurie/blog/blog.rss
https://tratt.net/laurie/news.rss

utf9k.net
https://utf9k.net/blog/rss.xml
https://utf9k.net/rss.xml

veerle.duoh.com
https://veerle.duoh.com/design-feed.rss
https://veerle.duoh.com/inspiration-feed.rss

veronique.ink
https://veronique.ink/feed/
https://veronique.ink/feed/?type=rss

werd.io
https://granary.io/url?url=https://werd.io/content/all/&input=html&output=atom&hub=https://bridgy-fed.superfeedr.com/
https://werd.io/?_t=rss
https://werd.io/content/posts?_t=rss

wizardzines.com
https://wizardzines.com/comics/index.xml
https://wizardzines.com/index.xml

write.as
https://write.as/davepolaschek/feed/
https://write.as/matt/feed/
https://write.as/zampano/feed/

www.allendowney.com
https://www.allendowney.com/blog/feed/
https://www.allendowney.com/wp/feed/

www.briandeconinck.com
https://www.briandeconinck.com/feed/
https://www.briandeconinck.com/notes/feed/

www.ekran.org
https://www.ekran.org/ben/wp/feed/
https://www.ekran.org/ben/wp/feed/?_=8177

www.ellyloel.com
https://www.ellyloel.com/articles.atom
https://www.ellyloel.com/feed.atom

www.gyford.com
https://www.gyford.com/phil/feeds/everything/rss/
https://www.gyford.com/phil/writing/feeds/posts/rss/

www.jeremycherfas.net
https://www.jeremycherfas.net/blog.atom
https://www.jeremycherfas.net/blog.rss

www.math.columbia.edu
https://www.math.columbia.edu/~dejong/wordpress/?feed=rss2
https://www.math.columbia.edu/~woit/wordpress/?feed=rss2

www.preposterousuniverse.com
https://www.preposterousuniverse.com/blog/feed/
https://www.preposterousuniverse.com/feed/

www.siennaeggler.com
https://www.siennaeggler.com/author/sienna/rss/
https://www.siennaeggler.com/rss/

www.sierz.co.uk
https://www.sierz.co.uk/blog/feed/
https://www.sierz.co.uk/reviews/feed/

www.somebits.com
https://www.somebits.com/linkblog/index.atom
https://www.somebits.com/weblog/index.atom

www.tekovic.com
https://www.tekovic.com/atom.xml
https://www.tekovic.com/rss.xml

xdg.me
https://xdg.me/index.xml
https://xdg.me/writing/index.xml

**Comment by winstonrc** [comment]
A few questions (with examples) that I think would be worth answering before making any changes:

1. Do these need to be manually checked one-by-one to confirm they all work?
Perhaps a script could be used to see if the feed pulls down data.

2. Given multiple feeds, is the blog specific feed the priority to keep?

> www.sierz.co.uk

> https://www.sierz.co.uk/blog/feed/

> https://www.sierz.co.uk/reviews/feed/

3. Given multiple formats for the feed (i.e. rss and atom both present in the list), is one type of format preferred?

> www.tekovic.com

> https://www.tekovic.com/atom.xml

> https://www.tekovic.com/rss.xml

4. Given multiple feeds that are very similar, which should be selected?

> honzadvorsky.com

> https://honzadvorsky.com/feed

> https://honzadvorsky.com/feed.xml

**Comment by vprelovac** [comment]
1. Any method is fine
2. Yes blog is preferred
3. No preference, lets keep shorter string perhaps
4. No preference, lets keep shorter string perhaps

**Comment by vprelovac** [comment]
Bitcoin or no is nowhere in the guidelines, do not make content judgements please this is about deduplication of feeds.

**Comment by winstonrc** [comment]
Yeah that's what I am doing. I just happened to notice that while looking for the canonical feed and remembered this comment in the README:
> The site must not contain any forms of monetization

**Comment by vprelovac** [comment]
You are correct, I should clarify it is non ad-monetized, donations are OK.
