### ISSUE TITLE
Guidance about microblogging and social platforms

### ISSUE THREAD

**Issue by v-p-b** [kagisearch/smallweb#163]
I'd like to ask for guidance about the eligibility of microblogs and other content feeds close to social-networks.

Specifically, most Fediverse software (Mastodon, Pleroma, Lemmy, etc.) publishes syndication feeds. Some of the content is explicitly defined as (micro)blogging (e.g. Mastodon), while others (like Lemmy) aren't, and it's safe to say that all content can also be considered as social media (as in Facebook) postings thanks to the connections provided by the ActivityPub protocol. 

I would definitely see value in indexing microblogs and other types of content (e.g. Lemmy posts can be useful resources), especially since discoverability on Fedivers is notoriously bad. On the other hand I expect (but wouldn't necessarily agree with) social media to be excluded.

Please clarify your stance on this! Thank you!

**Comment by vprelovac** [comment]
Can you share a few examples of what you would submit?

**Comment by v-p-b** [comment]
Sure: first of all my very selfish interest is to get my feed indexed: https://infosec.place/users/buherator/feed.atom

This is a random WriteFreely blog: https://blog.dtth.ch/nki/feed/

Here's a random Lemmy feed: https://infosec.pub/feeds/c/mokancan.xml (In this case we can have both "URL posts" (~redirects) and regular community posts that complicates things I guess)

**Comment by vprelovac** [comment]
I chceked it out and think the format is not appropriate. There is no 'Small Web' vibe about updates on a social media site.
