### ISSUE TITLE
What data source is used by RSS feed?

### ISSUE THREAD

**Issue by OlegWock** [kagisearch/smallweb#211]
Hello! I added Kagi Small Web RSS data feed (`https://kagi.com/api/v1/smallweb/feed`) to my reader and noticed that there are a few non-english sites (e.g. I have a lot of some chinese posts in my reader right now). I wanted to create PR to remove those sites, but it seem sites in question (`hktv1.vip` in this case) isn't present in smallweb list in this repo.

**Comment by vprelovac** [comment]
thanks for that, must be one of the sites got hacked and redirects. will look into it

**Comment by OlegWock** [comment]
There are multiple sites, some in french, german (though I won't be able to find them now). I'd like to help by creating PRs right away rather than bugging you about it :)

**Comment by vprelovac** [comment]
Please do that. This one I needed to look into as it does not appear in the feed list. I found the culprit it was  https://nuotsu.com/rss.xml
