### ISSUE TITLE
Add support for Wiby, the search engine for Classic Websites

### ISSUE THREAD

**Issue by Apocryphon** [kagisearch/smallweb#259]
[Wiby](https://wiby.me/about/) is a boutique search engine specializing in "older style pages, lightweight and based on a subject of interest," websites "reminiscent of the early internet." Pages are manually submitted by anonymous users. Its mission seems very in line with Kagi Small Web. Would a partnership to integrate Wiby somehow be in order?

There's a Wiby.me and a Wiby.org, which are probably identical.

**Comment by vprelovac** [comment]
Thanks for the suggestion. How would you imagination the integration?

**Comment by Apocryphon** [comment]
Could the Kagi search engine use Wiby as a source?

**Comment by vprelovac** [comment]
I do not believe it has an API?
