### ISSUE TITLE
Consider leaving Microsoft GitHub

### ISSUE THREAD

**Issue by toastal** [kagisearch/smallweb#27]
If we want to push for a smaller web not owned by US corporate control, shouldn’t this code be hosted on a libre platform ideal with federated patches? Y’all link sources like https://smallweb.page/why

> Modern Gatekeepers
> 
> Today, most of the time spent on the web is either on a small number of very dominant platforms like Facebook and LinkedIn, or mediated through them.

Why stop at blogs? Microsoft GitHub is trying to monopolize the coding space as much as Facebook, et al. are trying to do with web content. Note the way users can’t participate without an account, the platform’s Code search is disabled unless you are authenticated, there are upsell advertisements like the one for Microsoft GitHub Copilot in the UI, etc. DCVS (distributed version control systems) like Git don’t need to be kept behind a platform anymore than the small web. Why not apply the same rules/goals to this code forge (and then follow it with the chatroom)?

**Comment by vprelovac** [comment]
Respectfully, that is a rabbit hole with no end. If one is to take such attitude should they also stop using any software that is using github?

Rooting for small web does not mean one needs to be against other technology.

For example Kagi uses Google and even hosts on GCP - I think Google's technology and people are great, it is just the business model that is rotten and contributes to the deterioration of the web.

And Github at least has a business model that does not try to put more ads down your throat.

**Comment by toastal** [comment]
That’s a slippery slope to say leaving GitHub assumes dropping everything coming from it rather than being the change we’d like to see bringing the *distributed* back to distributed version control system (DVCS).

I can respect not moving, but the last statement about no ads is purely untrue.

I maintain a filter list (e.g. uBlock) for all the ads, upsells, social features so I’m aware of how much is really on this platform&mdash;since I can’t escape the platform. GitHub started embedding ads for Copilot in the main UI. They push their YouTube in the main UI. There’s upsells for Actions and the cloning button suggests you join their Code Space platform. Many projects have a dominant Sponsor button that they take a cut from (goodwill towards donating to projects/developers is good, but maybe not thru a this platform). They also fill the feeds with *Explore* features to keep users spending time on the platform along with other other social media tactics.
