### ISSUE TITLE
Query parameter to reduce the size of the feed?

### ISSUE THREAD

**Issue by Pinjasaur** [kagisearch/smallweb#279]
Unfortunately I'm unable to use the feed as-is because the ~25MiB size is too big for my feed reader (Miniflux).

<img width="862" alt="image" src="https://github.com/user-attachments/assets/3b873d7d-69fa-4bf3-8d93-ba6874ad8e7d">

Would it be possible to add an optional query parameter e.g. `?limit` to truncate the number of `<entry>` in the feed response? I took a stab at doing this myself (https://www.val.town/v/pinjasaur/smallweb) and while it works, I'd prefer to have the change in the upstream API.

I'd be happy to take a stab at implementing this feature, it's just not clear to me if this repo is also the same code that powers `kagi.com/api/v1/smallweb/feed/`.

**Comment by vprelovac** [comment]
Good idea! I found some time to implement it. It should be live in about 12 hours. Can I ask you to add this to Smallweb docs once you confirm it works as it should?

**Comment by Pinjasaur** [comment]
Sure thing, I'm happy to update the docs accordingly but I don't believe this feature is working as expected currently. I'm getting an HTTP 504:

```sh
$ curl https://kagi.com/api/v1/smallweb/feed/?limit=10
upstream request timeout
```

**Comment by vprelovac** [comment]
Found an issue with it, will deploy changes soon, please check again in 12h!

**Comment by Pinjasaur** [comment]
LGTM. Thanks for adding this. 🙂
