### ISSUE TITLE
Wrong links in README for repo files

### ISSUE THREAD

**Issue by mtomczynski** [kagisearch/smallweb#29]
In the info section you link to files smallweb.txt etc.
The links are for editing those files, not viewing them. Clicking the link prompts to fork the repo.

What's currently linked
https://github.com/kagisearch/smallweb/edit/main/smallweb.txt
vs
What should be linked
https://github.com/kagisearch/smallweb/blob/main/smallweb.txt

**Comment by vprelovac** [comment]
Thanks fixed
