### ISSUE TITLE
Deduplicate feed

### ISSUE THREAD

**Issue by vprelovac** [kagisearch/smallweb#296]
adactio.com
https://adactio.com/articles/rss
https://adactio.com/journal/rss

addyosmani.com
http://addyosmani.com/rss.xml
https://addyosmani.com/rss.xml

asawicki.info
https://asawicki.info/news_rss.php
https://asawicki.info/news_rss.php5

ascii.textfiles.com
http://ascii.textfiles.com/feed
https://ascii.textfiles.com/feed

astrid.tech
https://astrid.tech/atom.xml
https://astrid.tech/feed.xml

axio.ms
http://axio.ms//feed.xml
https://axio.ms/feed.xml

backreaction.blogspot.com
http://backreaction.blogspot.com/rss.xml
https://backreaction.blogspot.com/feeds/posts/default

benmccormick.org
https://benmccormick.org/feed.xml
https://benmccormick.org/rss/

bitsofco.de
https://bitsofco.de/feed/feed.xml
https://bitsofco.de/rss/

blog.cleancoder.com
http://blog.cleancoder.com/atom.xml
https://blog.cleancoder.com/atom.xml

blog.fogus.me
http://blog.fogus.me/feed/
https://blog.fogus.me/feed/

blog.pamelafox.org
http://blog.pamelafox.org/feeds/posts/default
https://blog.pamelafox.org/feeds/posts/default

blog.pesky.moe
https://blog.pesky.moe//index.xml
https://blog.pesky.moe/index.xml

blog.rongarret.info
http://blog.rongarret.info/feeds/posts/default
https://blog.rongarret.info/feeds/posts/default

blog.startifact.com
https://blog.startifact.com/atom.xml
https://blog.startifact.com/rss.xml

blog.vanillajava.blog
http://blog.vanillajava.blog/feeds/posts/default
https://blog.vanillajava.blog/feeds/posts/default

boston.conman.org
http://boston.conman.org/index.atom
https://boston.conman.org/index.atom

brandur.org
https://brandur.org/atoms.atom
https://brandur.org/nanoglyphs.atom

btxx.org
https://btxx.org/index.atom
https://btxx.org/index.rss

chrishannah.me
https://chrishannah.me/index.xml
https://chrishannah.me/rss/

coryd.dev
https://coryd.dev/feed.xml
https://coryd.dev/feeds/all

danq.me
https://danq.me/feed/
https://danq.me/kind/article/feed/

databasearchitects.blogspot.com
http://databasearchitects.blogspot.com/feeds/posts/default
https://databasearchitects.blogspot.com/feeds/posts/default

davidwalsh.name
https://davidwalsh.name/feed
https://davidwalsh.name/feed/atom

dfarq.homeip.net
https://dfarq.homeip.net/feed
https://dfarq.homeip.net/feed/

drwho.virtadpt.net
https://drwho.virtadpt.net/atom/feed.atom
https://drwho.virtadpt.net/rss/feed.xml

euroquis.nl
https://euroquis.nl//feed.xml
https://euroquis.nl/feed.xml

flower.codes
http://flower.codes/feed.xml
https://flower.codes/feed.xml

foobartel.com
https://foobartel.com/notes/feed
https://foobartel.com/stream/feed

freerangestats.info
http://freerangestats.info/feed.xml
https://freerangestats.info/feed.xml

fuzzyblog.io
http://fuzzyblog.io/blog/feed.xml
https://fuzzyblog.io/blog/feed.xml

georgemauer.net
http://georgemauer.net/rss.xml
https://georgemauer.net/rss.xml

harrycresswell.com
https://harrycresswell.com/articles/feed.xml
https://harrycresswell.com/feed.xml

havn.blog
https://havn.blog/categories/english/feed.xml
https://havn.blog/feed.xml

herbertlui.net
https://herbertlui.net/feed
https://herbertlui.net/feed/

holtwick.de
https://holtwick.de/atom.xml
https://holtwick.de/feed.xml

howonlee.github.io
http://howonlee.github.io/feed.xml
https://howonlee.github.io/feed.xml

huonw.github.io
http://huonw.github.io/blog/atom.xml
https://huonw.github.io/blog/atom.xml

ieftimov.com
http://ieftimov.com/index.xml
https://ieftimov.com/index.xml

infrequently.org
https://infrequently.org/feed
https://infrequently.org/feed/

jack-vanlightly.com
https://jack-vanlightly.com/?format=rss
https://jack-vanlightly.com/analyses?format=rss
https://jack-vanlightly.com/blog?format=rss

jakeyesbeck.com
http://jakeyesbeck.com/atom.xml
https://jakeyesbeck.com/atom.xml

jamesg.blog
https://jamesg.blog/feed.xml
https://jamesg.blog/feeds/posts.xml

jaspervdj.be
http://jaspervdj.be/rss.xml
https://jaspervdj.be/rss.xml

jaycarlson.net
https://jaycarlson.net/feed
https://jaycarlson.net/feed/

joe-steel.com
http://joe-steel.com/feed
https://joe-steel.com/feed

joshtronic.com
https://joshtronic.com/atom.xml
https://joshtronic.com/feed/

jpetazzo.github.io
http://jpetazzo.github.io/atom.xml
https://jpetazzo.github.io/atom.xml

khromov.se
https://khromov.se/feed
https://khromov.se/feed/

lea.verou.me
http://lea.verou.me/feed.xml
https://lea.verou.me/feed.xml
https://lea.verou.me/feed/

lucumr.pocoo.org
http://lucumr.pocoo.org/feed.atom
https://lucumr.pocoo.org/feed.atom

macwright.com
https://macwright.com/micro/rss.xml
https://macwright.com/rss.xml

malloc.dog
http://malloc.dog/rss.xml
https://malloc.dog/rss.xml

matt.might.net
http://matt.might.net/articles/feed.rss
https://matt.might.net/articles/feed.rss

matthewrocklin.com
https://matthewrocklin.com/atom.xml
https://matthewrocklin.com/blog/atom.xml

meyerweb.com
https://meyerweb.com/eric/thoughts/category/tech/rss2/full/
https://meyerweb.com/eric/thoughts/feed/?scope=full

mitxela.com
http://mitxela.com/feed
https://mitxela.com/feed

muratbuffalo.blogspot.com
http://muratbuffalo.blogspot.com/feeds/posts/default
https://muratbuffalo.blogspot.com/feeds/posts/default

nelson.cloud
https://nelson.cloud/index.xml
https://nelson.cloud/posts/index.xml

neopythonic.blogspot.com
http://neopythonic.blogspot.com/feeds/posts/default
https://neopythonic.blogspot.com/feeds/posts/default

nullprogram.com
http://nullprogram.com/feed/
https://nullprogram.com/feed/

oldvcr.blogspot.com
http://oldvcr.blogspot.com/feeds/posts/default
https://oldvcr.blogspot.com/feeds/posts/default

paragraph.xyz
https://paragraph.xyz/api/blogs/rss/@SoloSalon
https://paragraph.xyz/api/blogs/rss/@ccarella
https://paragraph.xyz/api/blogs/rss/@tudorizer

pepijndevos.nl
http://pepijndevos.nl/feed.xml
https://pepijndevos.nl/feed.xml

philip.greenspun.com
https://philip.greenspun.com/blog/feed/
https://philip.greenspun.com/blog/rss

preshing.com
http://preshing.com/feed
https://preshing.com/feed

rachelandrew.co.uk
https://rachelandrew.co.uk/archives/rss.php
https://rachelandrew.co.uk/feed/

radek.io
http://radek.io/rss
https://radek.io/feed.xml

ratfactor.com
http://ratfactor.com/atom.xml
https://ratfactor.com/atom.xml

rknight.me
https://rknight.me/feed.xml
https://rknight.me/subscribe/posts/rss.xml

roytang.net
https://roytang.net/blog/feed/rss
https://roytang.net/index.xml

ryanmulligan.dev
https://ryanmulligan.dev/blog/feed.xml
https://ryanmulligan.dev/feed.xml

swizec.com
https://swizec.com/blog/feed
https://swizec.com/rss.xml

thehistoryofcomputing.net
http://thehistoryofcomputing.net/rss
https://thehistoryofcomputing.net/rss

thenewleafjournal.com
https://thenewleafjournal.com/feed
https://thenewleafjournal.com/feed/

tilde.town
https://tilde.town/~dustin/index.xml
https://tilde.town/~kzimmermann/articles/atom.xml
https://tilde.town/~vilmibm/blog/feed.xml

timkadlec.com
https://timkadlec.com/atom.xml
https://timkadlec.com/remembers/atom.xml

two-wrongs.com
https://two-wrongs.com/atom
https://two-wrongs.com/feed

uridiumauthor.blogspot.com
http://uridiumauthor.blogspot.com/feeds/posts/default
https://uridiumauthor.blogspot.com/feeds/posts/default

utf9k.net
https://utf9k.net/blog/rss.xml
https://utf9k.net/rss.xml

werd.io
https://werd.io/content/posts?_t=rss
https://werd.io/feed

www.adambourg.com
http://www.adambourg.com/feed.xml
https://www.adambourg.com/feed.xml

www.autodidacts.io
https://www.autodidacts.io/rss
https://www.autodidacts.io/rss/

www.baldurbjarnason.com
https://www.baldurbjarnason.com/feed.xml
https://www.baldurbjarnason.com/index.xml

www.blogger.com
https://www.blogger.com/feeds/1788456751773099887/posts/default
https://www.blogger.com/feeds/31783628/posts/default

www.bram.us
https://www.bram.us/category/original-content/feed/
https://www.bram.us/feed/

www.brendangregg.com
http://www.brendangregg.com/blog/rss.xml
https://www.brendangregg.com/blog/rss.xml

www.bunniestudios.com
https://www.bunniestudios.com/blog/?feed=rss2
https://www.bunniestudios.com/blog/feed/

www.evanjones.ca
http://www.evanjones.ca/index.rss
https://www.evanjones.ca/index.rss

www.evanmiller.org
http://www.evanmiller.org/news.xml
https://www.evanmiller.org/news.xml

www.gkogan.co
https://www.gkogan.co/feed.xml
https://www.gkogan.co/rss/

www.gridbugs.org
https://www.gridbugs.org/feed.xml
https://www.gridbugs.org/rss.xml

www.jeremiahlee.com
https://www.jeremiahlee.com/feeds/atom.xml
https://www.jeremiahlee.com/feeds/jsonfeed.json

www.jeremykun.com
https://www.jeremykun.com/index.xml
https://www.jeremykun.com/rss/

www.math.columbia.edu
https://www.math.columbia.edu/~dejong/wordpress/?feed=rss2
https://www.math.columbia.edu/~woit/wordpress/?feed=rss2

www.os2museum.com
http://www.os2museum.com/wp/feed/
https://www.os2museum.com/wp/feed/

www.quirksmode.org
http://www.quirksmode.org/blog/atom.xml
https://www.quirksmode.org/blog/atom.xml

www.ribbonfarm.com
http://www.ribbonfarm.com/feed/
https://www.ribbonfarm.com/feed/

www.righto.com
http://www.righto.com/feeds/posts/default
https://www.righto.com/feeds/posts/default

www.schneier.com
https://www.schneier.com/blog/atom.xml
https://www.schneier.com/feed/

www.wilfred.me.uk
http://www.wilfred.me.uk/rss.xml
https://www.wilfred.me.uk/rss.xml

www.zachleat.com
https://www.zachleat.com/follow/
https://www.zachleat.com/web/feed
https://www.zachleat.com/web/feed/

www.zinzy.website
https://www.zinzy.website/feed.xml
https://www.zinzy.website/posts/index.xml

yifan.lu
http://yifan.lu/feed.xml
https://yifan.lu/feed.xml

zellwk.com
https://zellwk.com/feed.xml
https://zellwk.com/rss.xml

**Comment by vprelovac** [comment]
Any takers? :)

**Comment by dimeeentor** [comment]
Should it look like this?
```txt
00f.net
  https://00f.net/rss.xml
00formicapunk00.wordpress.com
  https://00formicapunk00.wordpress.com/feed/
0110.be
  https://0110.be/rss.xml
0180744d.maciej-litwiniuk-net.pages.dev
  https://0180744d.maciej-litwiniuk-net.pages.dev/index.xml
0fps.net
  https://0fps.net/feed/
0pointer.net
  https://0pointer.net/blog/index.atom
0ut3r.space
  https://0ut3r.space/atom.xml
0x1.pt
  https://0x1.pt/feed.xml
0x19.org
  https://0x19.org/posts/feed.php
```
[deduplicated_feeds.txt](https://github.com/user-attachments/files/17383072/deduplicated_feeds.txt)

**Comment by vprelovac** [comment]
just take the main feed, and remove duplicates from them (after checking which makes more sense) and submit a PR

**Comment by Silvenga** [comment]
@vprelovac Still need help here?

**Comment by vprelovac** [comment]
All good we are done thanks to laiz!
