### ISSUE TITLE
Should I flag sites that disallow embedding?

### ISSUE THREAD

**Issue by IllyaMoskvin** [kagisearch/smallweb#317]
Occasionally, I run into a website that presents this error:

![firefox_ljgLIZkbKh](https://github.com/user-attachments/assets/cc3e0d57-a061-4dd9-ac86-02afe3636400)

Error text: 

> To protect your security, www.loc.gov will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

Example site: https://www.loc.gov/item/global-legal-monitor/2024-11-20/sweden-supreme-court-overturns-mothers-prison-sentence-for-the-best-interests-of-her-child/

On [blog.kagi.com/small-web](https://blog.kagi.com/small-web), I see a criteria for a website to be included here:

> The site should be compatible with iframe embedding. If it’s not, we’ll still index it for our search results.

With that in mind, should I be using the "Flag" function to report sites which present this error? I feel kind of bad doing it: on other sites, I'm used to "flag" functionality being reserved for reporting rule-breaking, hate speech, and things like that. So I just want to clarify if the flag function here should be be used to flag such errors.

It might be helpful to have "Flag" show a popup where the user can select a reason and confirm the flag submission.

**Edit:** Related to #313.

**Comment by vprelovac** [comment]
Nothing to do. we have an algo to detect this but it is not trivial. most of the time it is successful.  loc.gov is not smallweb and will be removed.

**Comment by IllyaMoskvin** [comment]
Thanks, but aside from loc.gov specifically, can you confirm if we should use the the "Flag" function to report sites which disallow embedding? It's not the first time I've run into this error.

For example, after just a few clicks of next, I ran into another one and flagged it: https://alis.me/?p=74666
