### ISSUE TITLE
Smaller most appreciated feed

### ISSUE THREAD

**Issue by facundoolano** [kagisearch/smallweb#320]
Hi, I would like to include the appreciated rss feed in my reader but it seems to have too much content. Would it make sense to have a smaller feed with eg the N most appreciated posts of the day? Would you consider a PR with such a feature?

**Comment by vprelovac** [comment]
Appreciate feed usually has only 20-30 items. What do you mean by too much content?

**Comment by facundoolano** [comment]
My bad, I misinterpreted the amount after scrolling a few pages in my reader. Closing this.
