### ISSUE TITLE
Remove Cloudflare Blog from Small Web list

### ISSUE THREAD

**Issue by cloudrac3r** [kagisearch/smallweb#46]
Cloudflare is a billon-dollar company and controls all traffic on a significant fraction of websites globally. Regardless of how interesting the Cloudflare Blog is, there is no possibility of it being considered part of the "Small Web". It should be removed from Kagi's Small Web list.

**Comment by vprelovac** [comment]
@cloudrac3r can you submit a MR where it is removed?

**Comment by cloudrac3r** [comment]
Sure, I created PR #47 which will do this.
