### ISSUE TITLE
joelx.com does not meet quality requirements

### ISSUE THREAD

**Issue by Ekpyrotika** [kagisearch/smallweb#49]
Browsing The Small Web, I was served this: https://joelx.com/dead-children/18136/

Not sure how that meets anywhere near the quality criteria for the site. It's just grotesque.

**Comment by vprelovac** [comment]
I can understand how you can find this grotesque. I can also understand there may be other people would not. In general we do not review the 'flavor' the content unless it is NSFW (which is in the guidelines).

Small web is thousands of humans and some of them may be very different than you and have different views of the world than you, like in the real world.

**Comment by Ekpyrotika** [comment]
I don't really understand it. The lack of consistently not-right wing content in the list is inconsistent with a curated snapshot of the small web free of bias. Please feel free to close this -- I will find a new list.
