### ISSUE TITLE
Inoreader won’t load rss (worked for first day or two on launch)

### ISSUE THREAD

**Issue by camjc** [kagisearch/smallweb#72]
Hi,
Great initiative here! Keen to use the rss feed.
Getting this error on Inoreader:
> A feed could not be found at https://kagi.com/api/v1/smallweb/feed/. This does not appear to be a valid RSS or Atom feed

It was working for a day or two from launch, but then broken since.
I tried both with and without the trailing slash in the url.

Any ideas?
Much thanks!

**Comment by warpspin** [comment]
The feed is unusual in that it is very big. Maybe crosses resource limits in many readers.

**Comment by vprelovac** [comment]
Correct, the feed is just very big. My feed reader does handle it though.
