### ISSUE TITLE
Guidelines: Websites that do not work at all without JavaScript allowed?

### ISSUE THREAD

**Issue by lsomm** [kagisearch/smallweb#77]
I feel like even though their content might be enjoyable, some websites do not work at all (i.e. show no text) without JS. Isn't that against the small web spirit?

**Comment by lsomm** [comment]
I do not have a source and there probably is none; apart from my intuition. I was filing this issue to actually discuss the rules here, as the readme did not say that lack of JS was an issue. Is JS explicitly ok to be required by a site?

**Comment by vprelovac** [comment]
Websites that use JavaScript are allowed.
